### Roteiro do projeto.
### A partir do bloco "Lista de espera" ele reproduz o fluxo da feature:
### comprar o unico lugar da secao (esgota) -> entrar na fila -> cancelar o
### pedido -> o lugar volta a ficar disponivel e o primeiro da fila e notificado.

###
GET http://localhost:3000

###
GET http://localhost:3000/partners

###
POST http://localhost:3000/partners
Content-Type: application/json

{
    "name": "Partner 1"
}

###
@partner_id = 076a2ae5-b4ed-438d-89fc-e1a4b42372ba

###
GET http://localhost:3000/customers

### Cliente A - o que compra o ingresso
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 1",
    "cpf": "592.110.870-74"
}

###
@customer_id = 61f0ff6e-0bb1-4635-8899-4b88ce46975b

### Cliente B - o que entra na lista de espera
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 2",
    "cpf": "993.464.130-50"
}

###
@customer_id_b = 00000000-0000-0000-0000-000000000002

###
GET http://localhost:3000/events

###
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Event 1",
    "description": "Description 1",
    "date": "2020-01-01T00:00:00.000Z",
    "partner_id": "{{partner_id}}"
}

###
@event_id = 3181cb03-59e6-469a-9942-358b07882a72

###
GET http://localhost:3000/events/{{event_id}}/sections

### Secao com um unico lugar, para esgotar com uma compra
POST http://localhost:3000/events/{{event_id}}/sections
Content-Type: application/json

{
    "name": "Section 1",
    "description": "Description 1",
    "total_spots": 1,
    "price": 200
}

###
PUT http://localhost:3000/events/{{event_id}}/publish-all

###
@section_id = 42a5f5b1-30c5-4b2f-b9b8-84e5cc948542

###
PUT http://localhost:3000/events/{{event_id}}/sections/{{section_id}}
Content-Type: application/json

{
    "name": "Section 1 updateddddd",
    "description": "Description 1 updatedddd"
}

###
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots

###
@spot_id = 96298e63-5a38-4352-b97d-322259f10921

###
PUT http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots/{{spot_id}}
Content-Type: application/json

{
    "location": "Location 1 updateddddqqqq"
}

###
GET http://localhost:3000/events/{{event_id}}/orders

### Cliente A compra o unico lugar: a secao esgota
POST http://localhost:3000/events/{{event_id}}/orders
Content-Type: application/json

{
    "customer_id": "{{customer_id}}",
    "section_id": "{{section_id}}",
    "spot_id": "{{spot_id}}",
    "card_token": "tok_visa"
}

###
@order_id = 00000000-0000-0000-0000-000000000001

### Lista de espera - cliente B entra na fila da secao esgotada
POST http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/waiting-list
Content-Type: application/json

{
    "customer_id": "{{customer_id_b}}"
}

### Lista de espera - consultar a fila (entrada PENDING, na ordem de chegada)
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/waiting-list

### Cancelamento do pedido do cliente A
### Um unico POST dispara toda a cadeia:
### OrderCancelled -> EventSpotReleased -> SpotOfferedToWaitingCustomer ->
### SpotOfferedToWaitingCustomerIntegrationEvent -> RabbitMQ -> apps/emails
POST http://localhost:3000/events/{{event_id}}/orders/{{order_id}}/cancel

### Consequencia 1 - o lugar voltou a ficar disponivel (is_reserved = false)
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/spots

### Consequencia 2 - a entrada do cliente B esta NOTIFIED
GET http://localhost:3000/events/{{event_id}}/sections/{{section_id}}/waiting-list
